### ISSUE TITLE
新手，想咨询点问题

### ISSUE THREAD

**Issue by raindecloud** [allinu/Dell-7560-OC#1]
您好，感谢分享7560OC的efi。不过没太看懂这个使用方法。
“在线安装方法”这一部分是怎么用的呢？
跑对应的python脚本吗？
比如我是Catalina 10.15.7
就跑这一部分？
Catalina
./macrecovery.py -b Mac-CFF7D910A743CAAF -m 00000000000PHCD00
./macrecovery.py -b Mac-00BE6ED71E35EB86 -m 00000000000000000
会生成两个下载文件对吗？然后走安装教程？

**Comment by allinu** [comment]
@raindecloud 你好，这个[链接](https://github.com/luchina-gabriel/macrecovery)是在线安装的原项目地址，所谓的在线安装是，只下载引导启动的基础镜像，让后进入安装模式，需要联网下载安装，就像白苹果的重置电脑，联网在线重装的感觉是一样的，这种安装方式不需要很大容量的U盘，也会更加安全，系统更加完整。推荐使用此方法。

具体的使用步骤的话，就是安装python，然后clone本项目，运行这个macrecovery.py的文件，根据你需要的系统版本，执行相关的携带参数的指令即可，然后调整目录结构为README文件中的层级状态。

#### 我刚刚我把我的文件和原项目文件进行了同步修改，建议你重新clone 然后操作，我测试了BigSur 流畅运行

其他的相关问题请参照README文件，欢迎提问

**Comment by raindecloud** [comment]
@allinu 感谢大佬回复！
之前没有用过恢复模式在线安装这种方法，这次也学到了。
前两天为了稳妥写了装机U盘，还是使用U盘安装的方式，现在已经装好了，使用的您的EFI。
目前版本是Big Sur 11.5.2 (20G95)
笔记本是dell-7560-i5-7200U，使用的是94360CS2原装网卡
确实流畅运行，目前作为主力机使用，蓝牙Wi-Fi睡眠目前也没发现什么问题。
有一点小问题的是触摸板，之前使用clover 10.13-10.15时触摸板都比较顺滑，这次升级之后感觉触摸板有点延迟的感觉。
如果之后能精简efi或者做优化就更好了，现在好像比较多，兼容性更好但是比较臃肿。有时间我试着改改看。

**Comment by allinu** [comment]
@raindecloud 能精简那最好了，我也不是很懂，都是拼凑的文件，能帮到你就谢天谢地了，不推荐使用触控板，我用起来点击好像不太好用，都是外接鼠标使用
